### PR TITLE
Adde Google Colab and Tests

### PR DESCRIPTION
**Pull request by rohittp0**
1. Added `test.sh`
   - This script ensures that new commits meet the requirements of this repo.
   - Checks if a new line is added to `blackboard/addName.txt`.
   - Checks if the added line contains at most 10 characters ( including \n ).
   - Prevents deletion of existing lines.
   - Prevents editing files other than `blackboard/addName.txt`

 2. Added `.github/workflows/test_new_names.yml`
    - This is the GitHub actions file for the CI.
    - It runs `test.sh`
    - It ensures that every pull request only contains one commit.
  
 3. Updated  `blackboard/addName.txt`
    - This is a noncritical change.
    - Added my name to the file.
    - Was done for testing only.

### CODE REVIEW

**Review by LunaticHacker — CHANGES_REQUESTED** [review]
minor typo at [L28](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L28),[L29](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L29),[L34](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L34) and [L35](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L35) in test.sh

**Comment by rohittp0** [comment]
> minor typo at [L28](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L28),[L29](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L29),[L34](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L34) and [L35](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L35) in test.sh

Sorry, my bad. 
Fixed them.

**Comment by rohittp0** [comment]
> minor typo at [L28](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L28),[L29](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L29),[L34](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L34) and [L35](https://github.com/tinkerhub/mashithandu/blob/9a838bcff2e148afd984c9a6ad0cf5c627f90c70/test.sh#L35) in test.sh

Sorry, my bad. 
Fixed them.

**Comment by LunaticHacker** [comment]
The tests LGTM, but i think adding google colab kinda defeats the purpose of this repo. Thoughts @GopikrishnanSasikumar

**Comment by GopikrishnanSasikumar** [comment]
@rohittp0 I agree with @LunaticHacker we shouldn't introduce Google collab here.

**Comment by rohittp0** [comment]
@LunaticHacker @GopikrishnanSasikumar 

Ok, then I will move it to another branch. There is a meet with Kurian at 8 PM, I will update the PR after informing him.

**Comment by rohittp0** [comment]
There is also a proposal to set up git hooks to run the test locally before pushing.

**Comment by rohittp0** [comment]
@LunaticHacker @GopikrishnanSasikumar 

Removed Google Colab.

**Comment by rohittp0** [comment]
> There is also a proposal to set up git hooks to run the test locally before pushing.

I will implement this in the next pull request.

**Pull request merged**
